sops:
    kms: []
    gcp_kms:
    -   resource_id: projects/simplifield-platform-dev/locations/global/keyRings/sops/cryptoKeys/sops-key
        created_at: '2022-11-22T14:06:26Z'
        enc: CiQA52ZYG+DK8j0/I/xP1r4R69WA+hHku+HOTbx9/2/IHhwX7xwSSQC/NrscfuCkTlfrNmfKclbnLiTx7jTPPrCWpXRz2HE+OobmjWuW3lTP1nzssgx9+dGOe8rzwd9Tn/Ucz19Q8JmkHUX1BfIASGg=
    azure_kv: []
    hc_vault: []
    lastmodified: '2022-11-22T14:06:26Z'
    mac: ENC[AES256_GCM,data:ZTTM4+pm/vT8MHnl0z+iHYp28FBQmkrwUN4eQ6vwJHsuXhW2sp7JBkhJcU8r39+qrojCfQOQ/b++yp6fB9DgPZjKzOS+m+f2IWIWf/1q3XzILA+q2tyh0dH/AdikxA/ZXfbF+g+4E9JU5aN8kzE/H/c/618yTavQKbVbZh/sohM=,iv:5vdkTcYvXLxcIA6TbB8S0tNk4DWFUqA7S5QoEGPphWU=,tag:rr6sV3fd27xFwOxIJyUIlA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.6.1
